"""Render Devpost-ready English assets without inventing missing evidence."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from a64pilot.report.claims import (
    PRIMARY_CLAIM_ID,
    generate_claims,
    has_demonstrated_improvement,
)
from a64pilot.report.integrity import scan_text, validate_evidence_bundle, verify_claim_sources
from a64pilot.schemas import Claim


class SubmissionNotReady(RuntimeError):
    pass


def _read_json(path: Path) -> Any:
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def render_submission(
    *,
    project_root: Path | str = ".",
    allow_pending: bool = False,
    repo_url: str = "https://github.com/xiaodouzi666/AAutopilot",
    video_url: str | None = None,
) -> dict[str, Path]:
    root = Path(project_root)
    artifacts = root / "artifacts"
    artifacts.mkdir(parents=True, exist_ok=True)
    report = _read_json(artifacts / "report-data.json") or {}
    claims = report.get("claims", [])
    system = report.get("system") or _read_json(artifacts / "system-info.json")
    build = report.get("build") or _read_json(artifacts / "build-manifest.json")
    models = report.get("models") or _read_json(artifacts / "model-manifest.json")
    measured = bool(claims) and report.get("evidence_status") == "measured"
    if not allow_pending:
        records, evidence_errors = validate_evidence_bundle(artifacts, require_records=True)
        try:
            typed_claims = [Claim.model_validate(item) for item in claims]
        except Exception as exc:
            typed_claims = []
            evidence_errors.append(f"report claim schema: {type(exc).__name__}")
        evidence_errors.extend(verify_claim_sources(typed_claims, records))
        expected_claims = generate_claims(records, split_path=root / "demo/split.json")
        if [claim.model_dump(mode="json") for claim in typed_claims] != [
            claim.model_dump(mode="json") for claim in expected_claims
        ]:
            evidence_errors.append("report claims do not exactly match recomputed claims")
        if not has_demonstrated_improvement(typed_claims):
            evidence_errors.append(
                "the preregistered primary mean-TTFT claim does not have a positive "
                "confidence interval above zero"
            )
        missing = [
            name
            for name, present in (
                ("measured Arm64 claims", measured),
                ("system manifest", bool(system)),
                ("build manifest", bool(build)),
                ("model manifest", bool(models)),
            )
            if not present
        ]
        if missing:
            evidence_errors.append("submission evidence is incomplete: " + ", ".join(missing))
        if evidence_errors:
            raise SubmissionNotReady(
                "submission evidence failed strict validation: " + "; ".join(evidence_errors)
            )

    context = {
        "generated_at": datetime.now(UTC).isoformat(),
        "measured": measured,
        "repo_url": repo_url,
        "video_url": video_url,
        "claims": claims,
        "primary_claim_id": PRIMARY_CLAIM_ID,
        "system": system,
        "build": build,
        "models": models,
        "report": report,
        "category": "Cloud AI",
        "project_title": "AArch64 Autopilot: Self-Optimizing Agentic AI on Arm CPUs",
        "tagline": "Give it an Arm64 machine and an agent workload; it discovers a fast quality-preserving CPU configuration and generates the proof.",
    }
    environment = Environment(
        loader=FileSystemLoader(root / "templates"),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        autoescape=False,
    )
    writeup = environment.get_template("devpost.md.j2").render(**context)
    video = environment.get_template("video-script.md.j2").render(**context)
    checklist = environment.get_template("submission-checklist.md.j2").render(**context)
    final_path = artifacts / "devpost-writeup-final.md"
    video_path = artifacts / "video-script-final.md"
    checklist_path = artifacts / "submission-checklist.md"
    final_path.write_text(writeup, encoding="utf-8")
    video_path.write_text(video, encoding="utf-8")
    checklist_path.write_text(checklist, encoding="utf-8")
    # The root draft is the durable Devpost workflow handoff. Preserve a user-edited file.
    draft_path = root / "devpost-submission.md"
    if not draft_path.exists() or "Generated by AArch64 Autopilot" in draft_path.read_text(
        encoding="utf-8", errors="replace"
    ):
        draft_path.write_text(
            "<!-- Generated by AArch64 Autopilot; rerender with `make submission`. -->\n\n"
            + writeup,
            encoding="utf-8",
        )
    errors: list[str] = []
    for path in (final_path, video_path, checklist_path):
        errors.extend(scan_text(path))
    if errors:
        raise SubmissionNotReady("generated submission failed integrity scan: " + "; ".join(errors))
    return {
        "writeup": final_path,
        "draft": draft_path,
        "video_script": video_path,
        "checklist": checklist_path,
    }
